logging:
  level:
    root: INFO
#    org.springframework.test: INFO
#    org.springframework.test.context.junit4.SpringJUnit4ClassRunner: INFO
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
management:
  server:
    port: 8081

spring:
  profiles:
    active: test

---
spring:
  profiles: test
  main:
    banner-mode: "off"
    log-startup-info: false
  application:
    name: test-service-test
management:
  server:
    address: 127.0.0.1

---
spring:
  profiles: dev
  main:
    banner-mode: "off"
    log-startup-info: false
  application:
    name: test-service-dev

---
spring:
  profiles: prod
  main:
    banner-mode: "off"
    log-startup-info: false
  application:
    name: test-service

